### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by jubby2000** [jubby2000/infinotes#7]
- [x] Users can sign up, sign in, log out
- [x] Users can use a demo login to try the site
- [x] User can't use any features without logging in
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by s-pangburn** [comment]
- [x] The balance of the splash page is a little "off", make the "robot brain" text a little smaller, it sort of dominates the page right now (and maybe give it a little more margin on the left and top:
- [x] Also, the text beneath that one shouldn't be sans-serif font (or not a sans-serif that looks so much like Times New Roman), it's a little heavy-handed. Alternatively, you could set the color to grey so that it's a little less heavy on the page. Screenshot of what I mean:
![screen shot 2018-06-07 at 4 40 57 pm](https://user-images.githubusercontent.com/8031316/41131702-b4d8d716-6a71-11e8-853b-3f50e2a5afbe.png)
- [x] Your demo login animation is nice, but it types a little too slowly right now. I'm assuming it uses setTimeout or setInterval, so please set the interval to be shorter. Maybe half as long?

And... that's it! Great job Jacob! This is looking really fantastic!
