### ISSUE TITLE
PA Review: Notebooks

### ISSUE THREAD

**Issue by jubby2000** [jubby2000/infinotes#8]
- [x] Users can create notebooks
- [x] Users can delete notebooks
- [x] Users can view a list of their notebooks
- [x] Notebooks display a count of their associated notes (currently 0)

**Comment by s-pangburn** [comment]
Excellent job Jacob! This looks REALLY slick and is really, really polished overall!

Unfortunately, as much as I want to say that deletion is enough for now, the nature of your app is such that Notebooks will contain notes. Being unable to edit the title of the notebook becomes much more inconvenient once notes are in the picture, because deleting a notebook is much more of a pain (you have to move all the notes out, or just sacrifice those notes altogether). I'm going to have to request you add editing for notebook titles.

A similar thing goes for error handling. I was testing the app with gibberish titles and found it wouldn't let me create the notebook, because I had happened to put in the same title twice without realizing. I think it's somewhat likely a technical recruiter will test for this (while trying to break your app), so I will also request that you implement errors into your modal.

Once those are done though, feel free to move on!

- [x] User should be able to edit a notebook's title
- [x] Errors should display with duplicate/invalid titles

**Comment by s-pangburn** [comment]
🙌
