### ISSUE TITLE
PA Review: Notes

### ISSUE THREAD

**Issue by jubby2000** [jubby2000/infinotes#9]
- [ ] User can add new notes
- [ ] User can delete notes
- [ ] User can update notes
- [ ] User can view a list of notes (sorted by most recently edited)

**Comment by s-pangburn** [comment]
- [x] The font size in the new note form should be bigger. In fact (save the note titles) I would say fonts all-around (buttons, forms, etc) need to be a little larger, for those with poorer eyesight (this applies mainly to the Save and Cancel buttons as well as the Quill inputs, but all around I think a small font size bump couldn't hurt.)
- [x] See if you can't get your Quill form to stretch all the way across that giant div on the right side of the page, so it looks closer to Evernote (Alternatively, it looks like you can get a similar effect by figuring out how to remove the border from your Quill input. This is going to be a pain, I'm not going to lie, but I think the benefit to the overall presentation will be worth it.
  - EDIT: Basically I want it to look like this, with no clear borders between the input and the rest of the page:
![screen shot 2018-06-13 at 2 06 56 pm](https://user-images.githubusercontent.com/8031316/41378184-23af65ec-6f13-11e8-8b8c-0f28cf55419d.png)
- [x] I should be able to select the notebook from the edit view. Also the notebook select dropdown in your new view needs to be styled properly to resemble Evernote.
- [x] Even if I create a note in a notebook, the notebook count doesn't seem to update to reflect this. Also, clicking on your notebooks doesn't do anything. It should take me to a list of the notes for that notebook.
- [ ] Consider this a bit of a bonus challenge on my part, but if you can pull this off it will look make for a good thing to bring up during technical interviews. Instead of having a Save button for your notes in the edit view, just have the note save as you type using the onChange method. Now obviously this is going to make an absurd number of requests. For that I suggest you look into [debouncing](https://css-tricks.com/debouncing-throttling-explained-examples/), which is a way of grouping multiple event calls into a single action to improve performance. Marshall already implemented a form of this in his app, so if you have trouble, you can ask him for tips and advice 🙂

**Comment by s-pangburn** [comment]
We agreed that auto-save will be implemented later, so I'm closing this issue to signify this MVP as done 👍 Great work Jacob!
